### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [PipeWire/pipewire#115]
I would like to point out that identifiers like “[`__PIPEWIRE_LOOP_H__`](https://github.com/PipeWire/pipewire/blob/67e567b9c7c4c96fe55996062a83b5b907282035/src/pipewire/loop.h#L20 "Update candidate")” and “[`PW_TYPE_INTERFACE__Core`](https://github.com/PipeWire/pipewire/blob/67e567b9c7c4c96fe55996062a83b5b907282035/src/pipewire/interfaces.h#L61 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by wtay** [comment]
I will do that

**Comment by wtay** [comment]
I believe this is all fixed in the work branch

**Comment by elfring** [comment]
In which time range will this identifier renaming become officially released?
