### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [PipeWire/pipewire#117]
[Extra null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") at [a few source code places](https://github.com/PipeWire/pipewire/blob/9e60fd0b57f0607237ffd972f88d421eb56e7b5f/src/pipewire/stream.c#L529 "Update candidate: pw_stream_destroy()").
How do you think about to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle")?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```

**Comment by Hi-Angel** [comment]
You have pretty much described a patch. Would you mind to go ahead, and send a pull request with the changes?

**Comment by elfring** [comment]
Would you dare to try the mentioned software development tool out?

**Comment by Hi-Angel** [comment]
> Would you dare to try the mentioned software development tool out?

Well, unfortunately I am not a Pipewire contributor *(I have other projects that I care more about)*, so there's no point in me trying static analysis out on Pipewire code. But you're obviously excited about that idea, so you could try applying the tool to the code, and sending fixes for whatever Coccinelle would find. Sounds like easy patches and tremendously useful contribution!

**Comment by elfring** [comment]
Will the shown transformation approach be useful also for other software projects you are more interested in so far?

**Comment by Hi-Angel** [comment]
> Will the shown transformation approach be useful also for other software projects you are more interested in so far?

I doubt so. 1-st place ATM takes my interest in Way-Cooler, but it's written in Rust, so your advises are not applicable. The second place takes libinput, and yes, it's C. However they're already using static analysis extensively in their CI. And by grepping `free(` calls I can tell: there's no pattern your noticed in Pipewire.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/PipeWire/pipewire/commit/5c6bd8e5c7ebe39e6068456465877753f532cc38 "free() can handle NULL just fine").

A few update candidates can still be found by using a script for the semantic patch language.

```diff
diff -u -p a/src/pipewire/link.c b/src/pipewire/link.c
--- a/src/pipewire/link.c
+++ b/src/pipewire/link.c
@@ -70,8 +70,7 @@ static void pw_link_update_state(struct
 			     pw_link_state_as_string(old), pw_link_state_as_string(state), error);
 
 		link->state = state;
-		if (link->error)
-			free(link->error);
+		free(link->error);
 		link->error = error;
 
 		pw_link_events_state_changed(link, old, state, error);
diff -u -p a/spa/plugins/support/mapper.c b/spa/plugins/support/mapper.c
--- a/spa/plugins/support/mapper.c
+++ b/spa/plugins/support/mapper.c
@@ -146,10 +146,8 @@ static int impl_clear(struct spa_handle
 
 	impl = (struct impl *) handle;
 
-	if (impl->types.data)
-		free(impl->types.data);
-	if (impl->strings.data)
-		free(impl->strings.data);
+	free(impl->types.data);
+	free(impl->strings.data);
 
 	return 0;
 }
diff -u -p a/src/pipewire/stream.c b/src/pipewire/stream.c
--- a/src/pipewire/stream.c
+++ b/src/pipewire/stream.c
@@ -1229,10 +1229,8 @@ static void on_node_proxy_destroy(void *
 	clear_buffers(this);
 	clear_mems(this);
 
-	if (impl->format) {
-		free(impl->format);
-		impl->format = NULL;
-	}
+	free(impl->format);
+	impl->format = NULL;
 	if (impl->trans) {
 		pw_client_node_transport_destroy(impl->trans);
 		impl->trans = NULL;
```
