### ISSUE TITLE
Versioning SPA / co-installability in case of ABI/API breaks

### ISSUE THREAD

**Issue by julian-klode** [PipeWire/pipewire#13]
In case SPA ever breaks API or just ABI, a distribution cannot simply migrate from one version to the next with co-installability, but needs a flag day where all reverse dependencies are rebuild. This seems suboptimal to me.

**Comment by jbicha** [comment]
The latest release produces libspa-lib.so.0.108.0

Does that satisfy your concern?

**Comment by fsateler** [comment]
Hmm. I had not seen this before, but I think is the same as https://github.com/PipeWire/pipewire/issues/60

**Comment by wtay** [comment]
I think this can be closed now since #60 is fixed
