### ISSUE TITLE
[Packaging of pipewire] - would it be possible to add names such as "pipewire-0.2.6" to the release/downloads page?

### ISSUE THREAD

**Issue by rubyFeedback** [PipeWire/pipewire#154]
Hello pipewire folks,

First, props to making releases available at https://github.com/PipeWire/pipewire/releases - I know, we have git to download the latest and greatest of pipewire, but I like oldschool release tarballs in general.

Which brings me to this issue here

We can wget the tarball here: https://github.com/PipeWire/pipewire/archive/0.2.6.tar.gz

When you extract it, it becomes pipewire-0.2.6/.

It is not a big issue; I can automatically repackage it through scripts, but it would still be useful (to me) if the tarball name has the same name as the extracted directory.

If it would not be too much work, could versioned names be added as well, e. g. pipewire-0.2.6.tar.xz? If it is too much work for too little gain please just disregard this issue here altogether. I know that a few other projects make versioned tarballs available.

**Comment by pprkut** [comment]
There's a pretty much undocumented feature of github where you can force a tarball name:

https://github.com/PipeWire/pipewire/archive/0.2.6/pipewire-0.2.6.tar.gz

Versioned tarballs as release artifacts are still nice(r), but this should cover your use case I guess

**Comment by wtay** [comment]
I'm using the 

https://github.com/PipeWire/pipewire/archive/0.2.6/pipewire-0.2.6.tar.gz

link now when packaging for Fedora now and it works fine. I can't see a way to add this to
the releases page but you could also add this to your download scripts and avoid a rename.
