### ISSUE TITLE
Setting pipeline to NULL state closes input FD

### ISSUE THREAD

**Issue by benzea** [PipeWire/pipewire#155]
It seems that there was a change in pipewire between `pipewire-libs-0.2.6-1.fc30.x86_64` and `pipewire-libs-0.2.5-3.fc30.x86_64` which results in pipewire to try to use the already closed FD.

This can be reproduced using the below script. The main change here is to set the state to NULL after 500ms and then into playing state again after 1000ms. With the newer pipewire version the X11 window never opens while it does with the older version.

[xdp-remote-deskto.py.txt](https://github.com/PipeWire/pipewire/files/3297503/xdp-remote-deskto.py.txt)

**Comment by benzea** [comment]
In my case the NULL state change is coming from inside GstRTSPServer.

**Comment by deisi** [comment]
will this be merged into some kind of quick fix? Because it effects upstream projects like here:
https://github.com/benzea/gnome-network-displays/issues/37
