### ISSUE TITLE
Getting `unable to lock lockfile` Error On Make Run

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [PipeWire/pipewire#160]
Hi there, I've been curious to try out Pipewire so I followed some of the build instructions and have had some difficulties. I get this error message specifically:

```
SPA_PLUGIN_DIR=build/spa/plugins \
PIPEWIRE_MODULE_DIR=build \
PIPEWIRE_CONFIG_FILE=build/src/daemon/pipewire.conf \
build/src/daemon/pipewire
[E][module-protocol-native.c:418 lock_socket()] unable to lock lockfile '/run/user/1000/pipewire-0.lock': Resource temporarily unavailable (maybe another daemon is running)
[E][module.c:277 pw_module_load()] "build/src/modules/libpipewire-module-protocol-native.so": failed to initialize: Resource temporarily unavailable
[E][main.c:106 main()] failed to run config commands
make: *** [Makefile:11: run] Error 255
```

I'm admittedly very new to building daemons on linux systems. My system is currently running Manjaro Gnome and I have a Scarlett 2i2 as my audio interface, for what it's worth.

**Comment by wtay** [comment]
You might have to stop the system pipewire first with:

systemctl stop pipewire.socket
systemctl stop pipewire.service

**Comment by Eoin-ONeill-Yokai** [comment]
Ah yes, it turns out that pipewire was already installed on my system (didn't realize mutter was already using it as a dependency) but unfortunately it doesn't seem like I can stop the service. I get the following:

```bash
[eoin@eoin-manjaro Source]$ systemctl stop pipewire.socket
Failed to stop pipewire.socket: Unit pipewire.socket not loaded.
[eoin@eoin-manjaro Source]$ systemctl stop pipewire.service
Failed to stop pipewire.service: Unit pipewire.service not loaded.
```

**Comment by wtay** [comment]
You might also have to disable the system pipewire first with:

systemctl disable pipewire.socket
systemctl disable pipewire.service

**Comment by Eoin-ONeill-Yokai** [comment]
Ah yes that last command seemed to help with the locking error at least. Thanks for taking the time to help me out!
