### ISSUE TITLE
permit clients to export dmabuf to pipewire

### ISSUE THREAD

**Issue by barrysong6** [PipeWire/pipewire#173]
right now, I find weston, gnome mutter are copying framebuffers to 
```
static void
pipewire_output_handle_frame(struct pipewire_output *output, int fd, 
                             int stride, struct drm_fb *drm_buffer)
{
        struct pw_type *t = output->pipewire->t;
        struct pw_buffer *buffer;
        struct spa_buffer *spa_buffer;
        struct spa_meta_header *h; 
        void *ptr;

        if (pw_stream_get_state(output->stream, NULL) !=
            PW_STREAM_STATE_STREAMING)
                goto out;

        buffer = pw_stream_dequeue_buffer(output->stream);
       ..

        spa_buffer = buffer->buffer;

        if ((h = spa_buffer_find_meta(spa_buffer, t->meta.Header))) {
               ...
        }

        ptr = mmap(NULL, size, PROT_READ, MAP_SHARED, fd, 0); 
        memcpy(spa_buffer->datas[0].data, ptr, size);
        munmap(ptr, size);

        spa_buffer->datas[0].chunk->offset = 0;
        spa_buffer->datas[0].chunk->stride = stride;
        spa_buffer->datas[0].chunk->size = spa_buffer->datas[0].maxsize;

        pw_stream_queue_buffer(output->stream, buffer);
}

```
the memcpy to put the buffer into the queue of pw_stream_queue_buffer() leads to 100% CPU loading.
I am wondering whether it is possible for clients to queue the dmabuf fd into pw_stream.

**Comment by wtay** [comment]
The work branch can do this now.  Pass PW_STREAM_FLAG_ALLOC_BUFFERS to the stream and set the dma-buf fd in the buffers in the add_buffer event (and remove in remove_buffer again). This uploads the fds to the daemon so they can be shared. I tested this with a local v4l2 device exporting DMA-BUFs to PipeWire.

**Comment by wtay** [comment]
you probably need to allocate a fixed set of DMA-BUFS first, set the amount in the allocation query and then only render to those that you added to a buffer in add_buffer.

**Comment by barrysong6** [comment]
@wtay  thanks, vim. i have found the commit in work branch. but i failed to find an example code for clients. would you kindly share some example code for clients, like enabling PW_STREAM_FLAG_ALLOC_BUFFERS and queuing dmabuf to pipewire? I would appreciate very much.

**Comment by wtay** [comment]
I added an example here:

  src/examples/video-src-alloc.c

It exports memfd because that's easier than DMA-BUF and the principle should be the same.

**Comment by barrysong6** [comment]
@wtay , i noticed the autolink was removed in this commit:
```
commit bdeedad1d61ef7cec2ca23bb16538f16fc1ee654
Author: Wim Taymans <wtaymans@redhat.com>
Date:   Thu May 17 17:21:07 2018 +0200

    auto-link: remove obsolete module
```
without this, after i upgraded weston to use "work" branch, i found the link between weston and pipewiresrc couldn't be built. 
so what is the current way in 3.0 for pipewire to make a link?

**Comment by wtay** [comment]
Yes, auto-link was something from before we had a separate session manager.
Now the
session manager will create links between nodes. Normally the session
manager is started by
pipewire as stated in the pipewire.conf file with the exec statement.

To link, it uses some heuristics. The current example session manager in
src/examples/media-session.c
uses the node.target to find a node to link to, if that fails, it tries
matching a node based on category and
such.

If you use pipewiresrc path=<node-id> ! ... the session manager should link
this for you to this specific
node. In the screensharing case, you get the node-id from the portal for
the stream you requested and
then you can use that as input for pipewiresrc.

Hope this helps,
Wim

**Comment by 21cnbao** [comment]
@wtay thank you very much. actually i managed to build the link by media-session  after posting the question here, so i removed the post.
right now, our team is exporting weston dmabuf fd to pipewiresrc, it seems it is not that easy as well. will update you the progress soon.

**Comment by barrysong6** [comment]
@wtay we have managed to use dmabuf in weston and created the zero-copy from weston to pipewiresrc. now we faced a user permission issue. the data flow is as below:
weston -> pipewiresrc -> rtspd
if we run all of pipewire, weston and rtspd by root user, everything is ok. but if we run pipewire in root, and weston in graphis user, once weston connects to pipewire, pipewire will remove pipewire-0 and pipewire-0lock.
if we run pipewire, weston and rtspd by graphis user, we can't start the streaming due to some reasons under debugging.
it seems pipewire only supports clients use the exactly same username with the process pipewire?
do i have any way to bypass the username check?

**Comment by barrysong6** [comment]
@wtay one weird phenomenon i have seen is that if any process using pipewire is started by a non-root user, the user itself can't access its /proc/pid/root, /proc/pid/exe and /proc/pid/cwd even though the user owns this pid.
```
ls: /proc/15214/exe: cannot read link: Permission denied
```
