### ISSUE TITLE
pw_remote_connect_fd() API change causes fd leak

### ISSUE THREAD

**Issue by michaelolbrich** [PipeWire/pipewire#181]
With the 0.2.6 release, the `fd` passed to `pw_remote_connect_fd()` is closed when the object ist destroyed. Since 151b2b266e1dae3679584f38b954e4357cf1e5cc this no longer happens and the `fd` is leaked.

This happens for example with chromium. As a result, the port and node remain until the chromium exits.

**Comment by wtay** [comment]
I think it's better to not close the fd but I understand it breaks ABI. So before doing a release we should probably revert this then.

**Comment by wtay** [comment]
I could achieve the same thing with a property on the remote. So the fd is closed by default unless you set a property. The property would then be set in pipewiresrc because it wants to reuse the fd.
