### ISSUE TITLE
ownership of properties in pw_remote_export is inconsistent

### ISSUE THREAD

**Issue by gkiagia** [PipeWire/pipewire#187]
pw_remote_export takes a pw_properties pointer as an argument and passes it down to the registered export function.
When exporting a spa_device, the caller is responsible for freeing this.
When exporting a pw_node, the caller is responsible for freeing as well.
When exporting a spa_node, however, the underlying export func creates a pw_node that takes ownership of the properties and the caller should not free them.

This is inconsistent; it should be fixed and documented.

**Comment by wtay** [comment]
For me taking ownership of the properties makes more sense, I think we do that in general everywhere else.
