### ISSUE TITLE
spa-less meson build fails

### ISSUE THREAD

**Issue by pH5** [PipeWire/pipewire#198]
`meson build -Dspa=false` fails with:

`src/pipewire/meson.build:83:0: ERROR: Unknown variable "spa_inc".`

**Comment by wtay** [comment]
You can't run PipeWire with at least the basic SPA plugins. We should remove the option to disable spa.

**Comment by pH5** [comment]
[!199](https://gitlab.freedesktop.org/pipewire/pipewire/merge_requests/199)
