### ISSUE TITLE
Please make the Web site securely accessible over HTTPS

### ISSUE THREAD

**Issue by paulmenzel** [PipeWire/pipewire#20]
Currently, the domain is not listed in the certificate.

```
$ curl -I https://pipewire.org
curl: (51) SSL: no alternative certificate subject name matches target host name 'pipewire.org'
```

**Comment by FSMaxB** [comment]
The certificate is valid for github. That makes me think that it is using Github Pages. I don't think it is possible to have that work with https with a custom domain name.

**Comment by FSMaxB** [comment]
https://github.com/PipeWire/pipewire/tree/gh-pages

**Comment by wtay** [comment]
Yeah, github pages doesn't allow https with custom domains..

**Comment by rugk** [comment]
closing my issue as a duplicate https://github.com/PipeWire/pipewire/issues/40

**Comment by war59312** [comment]
See: Add HTTPS support to Github Pages including custom domains: https://github.com/isaacs/github/issues/156

Also, it's possible with CloudFlare....

How to serve a custom HTTPS domain on GitHub Pages with CloudFlare: *FREE*, secure and performant by default: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by wtay** [comment]
Should be fixed now using cloudflare.
