### ISSUE TITLE
Sharing video between apps (like Syphon)

### ISSUE THREAD

**Issue by stuaxo** [PipeWire/pipewire#21]
Linux VJ software is missing something like Syphon to easily take video from one arbitrary application and pipe it to another - will pipewire support this use case ?

**Comment by atagen** [comment]
Seconded! And it's probably worth noting that one thing about Syphon/Spout that makes them particularly useful to the VJing community is that they texture share on the GPU, rather than using system memory.

**Comment by toastbrotch** [comment]
+1, thanx

**Comment by wtay** [comment]
This is exactly what we want to do, share audio and video between apps. We should be able to pass around opaque textures on the GPU with fds.

**Comment by stuaxo** [comment]
Great news for everyone @ https://www.facebook.com/groups/linux.visual.arists/

I guess an implementation of the Syphon API could easily be built on top, allowing existing apps to be recompiled ... or possibly interop with Syphon apps running in Wine.

**Comment by doctea** [comment]
Any news or idea on how far off this is please?  What needs to be done to make it happen?  Keen!

**Comment by wtay** [comment]
To make this happen, someone needs to do the work,really. We've verified that we can send dmabuf around. Now we need some example app for doing GPU computation on it to demonstrate the possibilities.

**Comment by stuaxo** [comment]
So, I was reading some of these links -  

https://keithp.com/blogs/fd-passing/
https://wayland.freedesktop.org/architecture.html
https://airlied.livejournal.com/78704.html
https://www.khronos.org/registry/EGL/extensions/EXT/EGL_EXT_image_dma_buf_import.txt
https://patchwork.freedesktop.org/patch/21264/

So with EGL DMA Buf APIs, you can pass an FD and the texture will stay in the GPU, where does the DMA bit come into it ?

**Comment by wtay** [comment]
Closing this, let's assemble ideas on the Wiki page I made
