### ISSUE TITLE
pipewiresrc does not expose DMABuf

### ISSUE THREAD

**Issue by ndufresne** [PipeWire/pipewire#31]
While testing the release version on Fedora 27, I notice that pipewiresrc does not expose DMABuf (for the webcam case). This force copies in GStreamer.

```
[nicolas@skullcanyon ~]$ GST_GL_WINDOW=wayland GST_DEBUG=glupload:7 gst-launch-1.0 pipewiresrc path=4 ! glimagesink sync=0
0:00:00.023564884 15590 0x5644a132ab60 DEBUG               glupload gstglupload.c:1590:gst_gl_upload_new:<glupload0> Created new GLUpload for context (NULL)
Définition du pipeline à PAUSED...
Le pipeline est actif et n’a pas besoin de phase PREROLL…
Contexte de l’élément « sink » : gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayWayland\)\ gldisplaywayland0";
Passage du pipeline à la phase PLAYING…
New clock: pipewireclock0
0:00:01.562716798 15590 0x5644a131c140 DEBUG               glupload gstglupload.c:1767:_upload_find_method:<glupload0> attempting upload with uploader GLMemory
0:00:01.562790678 15590 0x5644a131c140 DEBUG               glupload gstglupload.c:1767:_upload_find_method:<glupload0> attempting upload with uploader Dmabuf
0:00:01.562830018 15590 0x5644a131c140 DEBUG               glupload gstglupload.c:1767:_upload_find_method:<glupload0> attempting upload with uploader UploadMeta
0:00:01.562848505 15590 0x5644a131c140 DEBUG               glupload gstglupload.c:1767:_upload_find_method:<glupload0> attempting upload with uploader Raw Data

```

**Comment by ndufresne** [comment]
I have also checked in master, it is the same. We use the generic GstFdAllocator to pass both the generic FD and the DMABuf. Kernel side though, this is really not the same type of object, so it would be pretty wrong to assume all FD are DMABuf. We need to use the GstDMAbufAllocator for the DMABuf instead.

**Comment by ndufresne** [comment]
Ok, I naively implement that in the src element, but then found out that the info isn't passed by the protocol. That's all a bit unfortunate, anyway, here's a first patch, will have to learn a bit more before I can come out with a pull request.

[0001-pipewiresrc-Expose-DMABuf-through-GstDMABufAllocator.patch.txt](https://github.com/PipeWire/pipewire/files/1448461/0001-pipewiresrc-Expose-DMABuf-through-GstDMABufAllocator.patch.txt)

**Comment by wtay** [comment]
Pushed you patch to master with an addition to free the dmabuf allocator. I get this now with the
launch line:

PIPEWIRE_DEBUG=4 SPA_PLUGIN_DIR=build/spa/plugins PIPEWIRE_MODULE_DIR=build/src/modules/ GST_GL_WINDOW=wayland GST_DEBUG=glupload:7 gst-launch-1.0 pipewiresrc ! glimagesink sync=0

Got context from element 'sink': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayWayland\)\ gldisplaywayland0";
Setting pipeline to PLAYING ...
New clock: pipewireclock0
0:00:00.810531028 19715      0x122aa80 DEBUG               glupload gstglupload.c:1775:_upload_find_method:<glupload0> attempting upload with uploader GLMemory
0:00:00.810583142 19715      0x122aa80 DEBUG               glupload gstglupload.c:1775:_upload_find_method:<glupload0> attempting upload with uploader Dmabuf

**Comment by ndufresne** [comment]
Thanks Wim, I also confirm it works as expected !
