### ISSUE TITLE
Is desktop desktop streming encrypted?

### ISSUE THREAD

**Issue by rugk** [PipeWire/pipewire#41]
I've read [your blog](https://blogs.gnome.org/uraeus/2017/09/19/launching-pipewire/), but I have still one question:
Sharing the desktop shares, of course, private things, so is the desktop streaming actually encrypted? 
If so which protocol is used? (I assume VNC or so can't be, as this is a new protocol, is not it?)

If you need a specific integration, just assume Fedora 27, where GNOME also exposes this feature in the settings.

**Comment by wtay** [comment]
PipeWire doens't do the actual streaming, it simply provides the video to applications that can then to encoding/streaming/encryption themselves.
