### ISSUE TITLE
0.1.6: spa/pod-parser.h missing in spa/include/spa/meson.build

### ISSUE THREAD

**Issue by treba123** [PipeWire/pipewire#43]
There's a bug in 0.1.6 concerning one of the include files. See (https://bugzilla.redhat.com/show_bug.cgi?id=1514955)

I can't create a direct PR against a tag, therefore here the patch file:
```
--- pipewire-0.1.6.orig/spa/include/spa/meson.build	2017-12-01 18:49:21.664915000 +0100
+++ pipewire-0.1.6/spa/include/spa/meson.build	2017-12-01 18:49:46.710105863 +0100
@@ -23,6 +23,7 @@
   'pod.h',
   'pod-builder.h',
   'pod-iter.h',
+  'pod-parser.h',
   'pod-utils.h',
   'props.h',
   'ringbuffer.h',

```

**Comment by Cogitri** [comment]
This was fixed in #29 not too long ago

**Comment by treba123** [comment]
Ah right. But unfortunately there was no new version for it, so I'm not sure whether package maintainers are aware of that fix :(

**Comment by Cogitri** [comment]
Huh? 1.7 has been released some time ago which contains the fix

**Comment by treba123** [comment]
Right, I meant something like 1.6.1. I thought the 1.7 version contains many more changes and I'm not sure whether all distributions just go on to 1.7. But if that's the intended bahiour, it's alright :)
Thanks for clarifying

**Comment by Cogitri** [comment]
Well, don't just take my word for it, but IMO it doesn't make too much sense for such a young project as pipewire to release point releases :)
