### ISSUE TITLE
Gnome Desktop screencast (no audio)

### ISSUE THREAD

**Issue by lineber** [PipeWire/pipewire#53]
"In Fedora 27 Workstation, PipeWire provides screen capture and screencast recording in GNOME Shell."
In recent times, using other distros, I noticed that the Gnome screencast feature also captures audio. It doesn't work with my Fedora 27 workstation. Doing a search I found that Ubuntu or other distro users would use a setting like:
`gsettings set org.gnome.shell.recorder`
but this will not work because the recorder is not know to the system.

Looking through the documentation, I cannot  seem to find how to turn on the audio portion of the Gnome screencast with Fedora 27 or PipeWire.

Please provide me with a url on fixing this, or if it doesn't work in Fedora 27 due to PipeWire, then fix this feature. It should configure automatically, tho.

**Comment by wtay** [comment]
Fedora 27 doesn't use PipeWire yet for anything...

Here is some information for adding audio to the video: https://fedoraproject.org/wiki/ScreenCasting

**Comment by lineber** [comment]
The Fedora team appears to be providing conflicting information. According to  [Paul W. Frields](https://fedoraproject.org/wiki/User:Pfrields?rd=PaulWFrields) this was added in Fedora 27 Workstation? 

[whats-new-fedora-27-workstation](https://fedoramagazine.org/whats-new-fedora-27-workstation/)

Here's the specific quote:

> In Fedora 27 Workstation, PipeWire provides screen capture and screencast recording in GNOME Shell.
