### ISSUE TITLE
libspa-lib.so does not match libspa-lib-0.1.pc

### ISSUE THREAD

**Issue by fsateler** [PipeWire/pipewire#60]
Hi,

The shared library seems to be missing a versioning used for the .pc file, which doesn't make much sense to me (pkgconfig file can be co-installed but the .so symlink can't). I think the library needs to follow libpipewire and rename to `libspa-0.1.so` ?

**Comment by jbicha** [comment]
@wtay This issue is blocking the upload of pipewire to Debian.

**Comment by jbicha** [comment]
@wtay Ping!

**Comment by real-amano** [comment]
Sadly this is blocking the pipewire inclusion in Ubuntu as well. And without the remote capabilities of piperwire it is possibly blocking Ubuntu 18.10 to move to Wayland again by default.

**Comment by Sunderland93** [comment]
Is there a workaround for this issue?
