### ISSUE TITLE
Possible free of uninitialized resource

### ISSUE THREAD

**Issue by Adonai** [PipeWire/pipewire#61]
On this [line](https://github.com/PipeWire/pipewire/blob/96fdfc86f7045699b14f204bba49376d610ee917/src/pipewire/remote.c#L313) there's a free of `error` object that can be not yet initialized.

Should this be fixed? Or am I missing something?

**Comment by rindeal** [comment]
it's either initialized or NULL, `free(NULL);` is a valid op

**Comment by Adonai** [comment]
didn't notice `calloc` in `pw_remote_new`
