### ISSUE TITLE
Unclear, even contradicting licensing

### ISSUE THREAD

**Issue by KAMiKAZOW** [PipeWire/pipewire#64]
* License headers say LGPL 2.0
* Manpage says LGPL 2.1
* LGPL file says 2.1
* There's a GPL file but I see no GPL code

Either change the manpages anf LGPL file to reflect what the headers say or change the headers to Lesser GPL 2.1.

Clarify which code is covered by the GPL. If none: Remove that file.

**Comment by KAMiKAZOW** [comment]
Ah, I was made aware of LGPL 2.1 file headers in SPA imported from BlueZ.

LGPL 2.0 and 2.1 are mostly the same except a few editorial tweaks and a rewritten preamble. I suggest changing the headers to "Lesser GPL 2.1" for uniformity.

**Comment by wtay** [comment]
It's all MIT now
