### ISSUE TITLE
float64 audio

### ISSUE THREAD

**Issue by aledomu** [PipeWire/pipewire#73]
In Pro Audio setups in other platforms, it's not that uncommon to see DAWs using 64-bit floating point audio data for the internal processing. Will this be feasable in the future between nodes or it's a big no-no?

**Comment by aledomu** [comment]
I noticed my own words. What I'm talking about is sending-receiving audio at float64 between apps so the processing of the whole audio system uses the result of those apps at max quality without any subsampling (which if done it would require another processing step per app, thus further increasing latency I guess).

**Comment by falkTX** [comment]
I am curious, do you have any of such "statistical" accuracy tests to show?
Editing audio in a float 32bit format *is* already the RAW format...

**Comment by fundamental** [comment]
Do you think that using 64 bit floating point numbers would produce any *audible* quality improvements over 32 bit floating point numbers?

> to avoid downsampling

Converting sample types and downsampling are very different concepts. If you're talking about downsampling you're talking about changing the sampling rate which does not appear to be the intent.

**Comment by x42** [comment]
It makes zero sense to use 64bit float to describe any audio signal.

For audio, samples of sound-pressure levels, 24bit is already more than sufficient to measure thermal noise at room temperature (~ -127dBm @48kHz bandwidth).  Even the best soundcards have a S/N ratio of 19-20 bits at best.

FLT_EPSILON corresponds to -138.5dBFS, there is zero use for any higher precision for audio.

Please someone with permissions to close this issue, stop this. This is not helpful for PipeWire development.

**Comment by aledomu** [comment]
What I don't understand is why it is desirable to decide for pro-audio app/plugin developers whether this is worth it to make use of or not (in case it is implemented), or in other words, to "know better" than them. I think it is much better to let them choose and empower them with an audio backend that can take their throughput without any downsampling nor sample type conversion (you were spot on there @fundamental , my bad). In fact, if two apps/plugins work at float64 internally and you chain them with PipeWire (or JACK for the matter) as things are right now, there are two steps of needless sample type conversion which add a few CPU cycles (I don't know how much and whether there would be any relevant performance hit in certain scenarios).

Since I already talked with Wim about this and he told that it's less complicated to implement than it seems and that it's possible to do without having to rework anything, I'm closing this.

**Comment by abique** [comment]
There are places where you want to use 64 bits floating point in your DSP (filters, ...), but it is unlikely for your audio output.

Your sound card is likely to take 16 or 24 bits per sample for your inputs/outputs.

**Comment by aledomu** [comment]
@abique Absolutely, I wasn't talking at all about the sound card. I feel I haven't made this point clear enough. It is just about the DSP stuff (and keeping the throughput of each app/plugin as intact as possible to the next app/plugin and mixing audio at the highest quality format that is given without topping on float32). Of course doing this for the sound card is utterly silly.

**Comment by aledomu** [comment]
My answer is that it's up to those who will build on top of PipeWire to decide if it's advantageous for them or not. Note that this would be toggleable, not the new default. If it can't be, then forget about it.

**Comment by diovudau** [comment]
> What I don't understand is why it is desirable to decide for pro-audio app/plugin developers whether this is worth it to make use of or not (in case it is implemented), or in other words, to "know better" than them

You may be unaware that at least three actual audio developers have answered in this discussion.  The implicit discussion is that this is purely marketing voodoo of you cited sources and all known science and audio processing history favours that view. It is your claim that 64 bit results in better audio thus it is your responsibility to proof that claim.

**Comment by x42** [comment]
The only reason for using 64bit float for an audio-signal is marketing and sales.

While there are algorithms that benefit or require internal double-precision for coefficients or local state, it doesn't make sense for any raw audio signal - even not in the digital domain between processors.   32bit float (IEEE 754) has a signal/noise ratio of around 144 dB  (without dithering) over a dynamic range of about 1540 dB.
Also keep in mind that when using the SIMD instructions on a x86_64 CPU, you can get twice as much work done using 32bit floats compared to 64bit floats.

So let's sell the same plugin again, now with 64bit DSP (bigger numbers are better right?),  and then sell a new faster PC, too

**Comment by aledomu** [comment]
@diovudau The only proof that's needed here is how much of an audible difference it does, and in what circumstances. I don't have the time nor resources to do so, hence why I just state it results in "better" (as in more precise) audio **from a purely mathematical point of view**. I don't claim anything about how noticeable it is (which except in extreme corner-cases, it might not). With my equipment it isn't. These links might explain better than me (the first is an "actual audio developer", if that's your bare minimum to take anything seriously):
* <https://www.steinberg.net/forums/viewtopic.php?t=126325#p688768>
* <https://www.steinberg.net/forums/viewtopic.php?p=687057#p687057>
* <http://www.meterplugs.com/blog/2017/02/03/does-64-bit-summing-sound-better.html>

After all the answers, I tried to understand a bit better the implications of the format negotiation that PipeWire does. It seems to me mixing (if required) could be done at this quality only on those places in the stream path where it is required by the nodes (and that is a decision from the DSP devs themselves).

@x42 I get your point and I understand you have strong opinions about how you develop your plugins (which are great BTW), and possibly they are (mostly) right. I won't change your mind about that, so keep writing plugins with float32 I/O if you think it's best.

However, since we are at the subsystem level of the stack, I think it's not right to enforce our opinions on other (future) developers. I think the important questions here are:
* Is it very costly to implement it? From Wim I understood it isn't.
* Do you think it's any good? Use it (as a dev).
* Do you think it's BS? Don't.

And everybody is happy. If the devs/users make a bad choice, let them fail (not in a catastrophic way). When they notice the performance dropping hilariously, they will follow the _Right Way_ if there is little benefit to it. Just delegate that decision.

You might fear the economical/social issues that may arise from making this a possibility, but even in the commercial realm just a few plugins really do this, and when they do (always as an option) they warn you about how horrible the performance is and that it is only to render the track. As a side note, supposedly Reaper processes and mixes the tracks at float64 but I don't see the performance dropping hard, which, based on your statements, confuses me (unless it is only that way when rendering, not in real-time). On the same line, more commercial DAWs are implementing that feature and VST3 is taking off (which can do float64 I/O), so I don't think we can stop that threat (if it's any real) from Linux with its market share.

**Comment by x42** [comment]
> I think it's not right to enforce our opinions on other (future) developers.

It is not an opinion. it is physics and CPU architecture.

And yes, we should not encumber future developers with this, not even pipewire devs in the near future. 

Also keep in mind that pipewire is a device abstraction (not a DAW), provides an API to developers and is GNU/Linux only.

The big issue that we have on Linux is the lack of a single unified audio API stack. I'm already very pessimistic that PipeWire can fill that need and eventually deprecate others. Adding 64bit as optional audio-format  would just add more overhead to an already over-complicated API, and it really is just overhead with zero benefit.

PS. and yes I do know about Reaper's sum bus, and VST3 etc..

**Comment by v-fox** [comment]
While I agree that in general 64bit audio processing is massive overkill I can't not point out that whole "24 BITS ARE ENOUGH FOR EVERYONE!1" argument, that everyone quick to throw out when someone brings up audio, is getting weird. When was last time you saw someone harping about rgb16f or even "insane" rgba32f (those are 32f **per channel of each pixel**, by the way, so 4\*32f\*\<resolution> per frame) video formats so adamantly ? Where are people yelling about how TN LCD panels can't show past rgb6, VA/IPS - rgb8 and only the most expensive ones - real rgb10 ? And how about "cinematic" 30 frames per second and "silly" >100 fps displays when most panels and GPUs can barely make honest 60 ?

Personally, I would be happy to just get rid of PA and JACK's shortcomings but still…

**Comment by abique** [comment]
I read that it has 32bit float buffers internally, and then it has to convert to the sound card sample format.
This thread should be closed, it is a pure waste of time.

**Comment by aledomu** [comment]
@abique I closed it way before this thread became the clusterfuck it is, which has been essentially people conflating the performance implications with the decision of what's the right accuracy/performance balance as facts and me trying to make the point that app devs should be able to choose which balance is right for them because it isn't 100% a fact.

Anyway, I thought it throughly and **maybe** the only reasonable thing to do is expose an option to enable 64-bit summing in the `dsp` subgraph, but keep audio samples at float32 as it is now. Not a big deal if it's not done either: <https://www.meterplugs.com/blog/2017/02/03/does-64-bit-summing-sound-better.html>

There's only one real-case scenario where float32 IPC might be worse for performance: VST3 plugins with float64 I/O (VST3 allows that) that are compiled for Linux as well. If a plugin loader hosts two of those exposed individually to the graph and interconnected, then there are two unnecessary sample conversions (and what will be processed is float64 audio anyways). Unless going f64 -> f32 is faster than writing the extra 32 bits on each sample, there's some (probable tiny) overhead. We can tell plugin devs "it's not right", but since they develop for other platforms which are able to do float64 and have a much greater market share, they will ignore it, which proves my point: it's pointless to decide for them. Having read the wiki about the sync API for pro-audio apps, my guess is that there would be at minimum two additions needed to the API: `supports_f64_bool(input node)` and another one for sending float64 audio samples.

Of course, there is very little reason for the DSP node to provide and/or consume float64 audio. No contest.

This will be my last answer, so please those who want to follow on here keep it as productive and informative as you can (and if you think this is a waste of time just ignore this thread, telling others to shut up when there's no off-topic nor insults is... uncomfortable to say the least).

**Comment by x42** [comment]
@aledomu all the articles that you've referenced so far are just mis-information. That meterplugs.com article is also wrong in some cases.  @v-fox : comparisons with video are not relevant at all.

**Comment by v-fox** [comment]
> @v-fox : comparisons with video are not relevant at all.

When you do any heavy I/O processing of importance, to keep distortion statistically-insignificant you do that from twice the target precision to all what your system allows, depending on how practical it is or how paranoid you are. Sight and hearing are human I/O interfaces to hardware, with tactile sensation having insignificant role too, so it looks pretty damn relevant **to me**. In video stream processing and rendering much more impractical precisions, upconversion on input and oversampling are common and nothing to be frowned upon, yet audio fanatics allow themselves such violently arrogant reactions. The only true counter-argument you could put on that is the fact that video processing does incur pretty heavy loses at times and sight is much more sensitive than hearing. On the other hand: *what if your target audio processing range is not 0-120db but 0-60db or even 0-30db out of whole recording ?* Wouldn't you want the whole thing to have more headroom for screwing it up less ? Same goes for sampling but there, luckily, up limit is already as high as a sky.

But wasn't even I'm talking about algorithms, it's about your collective attitude. You stage yourselves as championing facts but come off no better than a typical audiophile-schizoid trying to assert "clarity" of tube-amps and "sound" of wires. You're not as rational as you seem to believe either and your points are not as universal as you like to think. So have some goddamn decency and respect for other's opinions.
