### ISSUE TITLE
VST Linux plugin loader as wrapper

### ISSUE THREAD

**Issue by aledomu** [PipeWire/pipewire#74]
Is a VST plugin loader as a wrapper planned, like in the case of LADSPA and LV2? With the open-source release of the VST3 SDK from Steinberg this might get interesting in the future: <https://github.com/steinbergmedia/vst3sdk>

**Comment by falkTX** [comment]
VST2 is not opensource, and the VST3 open variant is GPLv3 only.
This would mean "bumping" the entire PipeWire license just because of a small feature...

I would rather not have reasons to use VST3 on Linux.
Leave that ugly monster to closed platforms please.

**Comment by aledomu** [comment]
Yeah, I realised that afterwards. Even without that, I'm not really sure if it's that good of an API.

Whatever, it's actually a horrible idea. What would be cool instead is if the SPA API could be used outside of PipeWire. I remember somewhere here on the issues that it is theoretically possible.

Closing this now.
